const ACTION_TYPES = {
  RECIPES_GET_ALL: 'RECIPES_GET_ALL',
  RECIPES_CREATE: 'RECIPES_CREATE',
  RECIPES_FILTER: 'RECIPES_FILTER',
  RECIPES_SORT: 'RECIPES_SORT',
  RECIPES_GET_USERS_CREATED: 'RECIPES_GET_USERS_CREATED',
  RECIPES_GET_USERS_SAVED: 'RECIPES_GET_USERS_SAVED',
  RECIPES_CREATE_COMMENT: 'RECIPES_CREATE_COMMENT',
  RECIPES_MODIFY: 'RECIPES_MODIFY',
  RECIPES_DELETE: 'RECIPES_DELETE',
  RECIPES_LIKE: 'RECIPES_LIKE',

  USER_UPDATE: 'USER_UPDATE',
  USER_UPDATE_PHOTO: 'USER_UPDATE_PHOTO',
  USER_SIGN_IN: 'USER_SIGN_IN',
  USER_SIGN_OUT: 'USER_SIGN_OUT',
  USER_SAVE_RECIPE: 'USER_SAVE_RECIPE',
  USER_SAVE_COOKBOOK: 'USER_SAVE_COOKBOOK',
  USER_CHANGE_BIO: 'USER_CHANGE_BIO',
  USER_CHANGE_NAME: 'USER_CHANGE_NAME',
  USER_CHANGE_EMAIL: 'USER_CHANGE_EMAIL',
  USER_CHANGE_PASSWORD: 'USER_CHANGE_PASSWORD',
  USER_CHANGE_PHOTO: 'USER_CHANGE_PHOTO',
  USER_SIGN_UP: 'USER_SIGN_UP',
  USER_DELETE: 'USER_DELETE',
};

export default ACTION_TYPES;
