const ACTION_TYPES = {
  RECIPE_GET_ALL: 'RECIPE_GET_ALL',
  RECIPE_DELETE: 'RECIPE_DELETE',
  RECIPE_UPDATE: 'RECIPE_UPDATE',
  RECIPE_CREATE: 'RECIPE_CREATE',
  RECIPE_SORT: 'RECIPE_SORT',
  RECIPE_FILTER: 'RECIPE_FILTER',

  COOKBOOK_GET_ALL: 'COOKBOOK_GET_ALL',
  COOKBOOK_DELETE: 'COOKBOOK_DELETE',
  COOKBOOK_UPDATE: 'COOKBOOK_UPDATE',
  COOKBOOK_CREATE: 'COOKBOOK_CREATE',
  COOKBOOK_SORT: 'COOKBOOK_SORT',
  COOKBOOK_FILTER: 'COOKBOOK_FILTER',

  USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE',
  USER_LOG_IN: 'USER_LOG_IN',
  USER_LOG_OUT: 'USER_LOG_OUT',
  USER_GET_RECIPES: 'USER_GET_RECIPES',
  USER_GET_COOKBOOKS: 'USER_GET_COOKBOOKS',
};

export default ACTION_TYPES;
