const ACTION_TYPES = {
  RECIPE_GET_ALL: 'RECIPE_GET_ALL',
  RECIPE_DELETE: 'RECIPE_DELETE',
  RECIPE_UPDATE: 'RECIPE_UPDATE',
  RECIPE_CREATE: 'RECIPE_CREATE',

  COOKBOOK_GET_ALL: 'COOKBOOK_GET_ALL',
  COOKBOOK_DELETE: 'COOKBOOK_DELETE',
  COOKBOOK_UPDATE: 'COOKBOOK_UPDATE',
  COOKBOOK_CREATE: 'COOKBOOK_CREATE',

  USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE',
  USER_GET: 'USER_GET',
};

export default ACTION_TYPES;
