const ACTION_TYPES = {
  RECIPES_GET: 'RECIPES_GET',
  RECIPE_CREATE: 'RECIPE_CREATE',
  COOKBOOKS_GET: 'COOKBOOKS_GET',
  USER_UPDATE: 'USER_UPDATE',
  USER_LOG_OUT: 'USER_LOG_OUT',
};

export default ACTION_TYPES;
